#pragma once
#ifndef FP_GLOBAL_H
#define FP_GLOBAL_H

#define FP_CLEAR_COLOR 0.0f, 0.05f, 0.15f, 0.55f
#define FP_MAX_LIGHTS 3
#define FP_OBJECT_RADIUS 20.0f
#define FP_DEFAULT_LIGHT_SCALE 1.0f

// For particle Init
#define FP_NUM_PARTICLES_X 12
#define FP_NUM_PARTICLES_Y 12
#define FP_NUM_PARTICLES_Z 12
#define FP_NUM_PARTICLES FP_NUM_PARTICLES_X * FP_NUM_PARTICLES_Y * FP_NUM_PARTICLES_Z

#define FP_PARTICLE_SPACING_X 1.0f
#define FP_PARTICLE_SPACING_Y FP_PARTICLE_SPACING_X
#define FP_PARTICLE_SPACING_Z FP_PARTICLE_SPACING_X


// For simulation
#define FP_GLASS_RADIUS 12.0f
#define FP_GLASS_FLOOR -20.0f

#define FP_DEFAULT_GRAVITY D3DXVECTOR3(0.0f, 1 * -9.81f, 0.0f)
#define FP_DEFAULT_FLUID_SMOOTHING_LENGTH 3.0f//0.01f
#define FP_DEFAULT_FLUID_COLLISION_RADIUS 3.0f
#define FP_DEFAULT_FLUID_GAS_CONSTANT_K 300.0f
#define FP_DEFAULT_FLUID_SURFACE_TENSION 0.0015f//0.0003f
#define FP_DEFAULT_FLUID_GRADIENT_COLORFIELD_THRESHOLD 0.075f
#define FP_DEFAULT_FLUID_VISCOSITY 0.002f
#define FP_DEFAULT_FLUID_PARTICLE_MASS 0.00020543f
#define FP_DEFAULT_FLUID_REST_DENSITY_COEFFICIENT 5.0f // TODO: tune
#define FP_DEFAULT_FLUID_DAMPING_COEFFICIENT 0.99f // TODO: tune
#define FP_DEFAULT_INITIAL_CELL_CAPACITY 10
#define FP_INITIAL_GRID_SIDELENGTH 50
#define FP_INITIAL_GRID_CAPACITY FP_INITIAL_GRID_SIDELENGTH \
    * FP_INITIAL_GRID_SIDELENGTH * FP_INITIAL_GRID_SIDELENGTH
#define FP_FLUID_MAX_POS 150.0f

// For simulation debug:
#define FP_DEBUG_MAX_FORCE 0.5f
#define FP_DEBUG_MAX_FORCE_SQ FP_DEBUG_MAX_FORCE * FP_DEBUG_MAX_FORCE


// For rendering
#define FP_RENDER_DEFAULT_SPRITE_SIZE 1.0f
#define FP_DEFAULT_ISOVOLUME_VOXELSIZE 0.9f
#define FP_DEFAULT_ISO_VOLUME_BORDER 5.0f
#define FP_DEFAULT_MC_ISO_LEVEL 0.024f
#define FP_INITIAL_ISOVOLUME_SIDELENGTH 200
#define FP_MC_MAX_TRIANGLES 1000000
#define FP_MC_MAX_VETICES FP_MC_MAX_TRIANGLES * 3
#define FP_ISO_VOLUME_GROW_FACTOR 0.2f
#define FP_ISO_VOLUME_SHRINK_BORDER 0.8f
#define FP_INITIAL_ISOVOLUME_CAPACITY FP_INITIAL_ISOVOLUME_SIDELENGTH \
    * FP_INITIAL_ISOVOLUME_SIDELENGTH * FP_INITIAL_ISOVOLUME_SIDELENGTH

#endif
